version: '3.4'

services:
  catalogdb:
    container_name: catalogdb    
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/dir   
      
  basketdb:
    container_name: basketdb    
    ports:
      - "6379:6379"
  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=Discountdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  pgadmin:
    container_name: pgadmin
    environment:    
      - PGADMIN_DEFAULT_EMAIL=nasir.islam@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin@123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  portainer:
    container_name: portainer    
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
     -  /var/run/docker.sock:/var/run/docker.sock 
     -  portainer_data:/data     
      
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings:ConnectionString=mongodb://catalogdb:27017   
    ports:
      - "8000:80"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CacheSettings:ConnectionStrings=basketdb:6379   
    ports:
      - "8001:80"

